### ISSUE TITLE
Seeking guidance on using Java BigTable IO connector in a Python pipeline

### ISSUE THREAD

**Issue by sayakpaul** [chamikaramj/multi-language-pipelines#1]
Hi @chamikaramj. Thanks for open-sourcing this project. 

I am currently working on a project for my organization that uses the Beam Python SDK but wants to read data from BigTable. Most of the resources that I have seen on the internet first define a transform class in Java (say) and then show it could be used from the Python SDK. However, I couldn't find how I could use a factory transform ([this](https://beam.apache.org/releases/javadoc/2.1.0/org/apache/beam/sdk/io/gcp/bigtable/BigtableIO.html) for example) and use from the Python SDK. 

If you could point me in the right direction, I would be grateful.

**Comment by chamikaramj** [comment]
Sorry, this is my private repo not an open source project.

For developing using Beam multi-language transforms, please see the guide here: https://beam.apache.org/documentation/programming-guide/#create-x-lang-transforms

We also have a quickstart guide here: https://beam.apache.org/documentation/sdks/python-multi-language-pipelines/

**Comment by sayakpaul** [comment]
As far as I understand it, this is an open-source project which is why I was able to discover it and comment. In case it was private, I would not have been able to do that.

**Comment by chamikaramj** [comment]
Closing since there's a discussion in Beam user list on this which is the right channel.
